# Generated by Django 5.1.3 on 2024-11-15 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('DestinationId', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Region', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('TourId', models.IntegerField(primary_key=True, serialize=False)),
                ('TourName', models.CharField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MaxTravellers', models.IntegerField()),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Nights', models.IntegerField()),
                ('Days', models.IntegerField()),
                ('Destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('BookingId', models.IntegerField(primary_key=True, serialize=False)),
                ('User', models.CharField(max_length=100)),
                ('Departure', models.CharField(max_length=100)),
                ('BookingDate', models.DateField(auto_now_add=True)),
                ('TravelDate', models.DateField()),
                ('Status', models.CharField(default='Pending', max_length=20)),
                ('Tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tour')),
            ],
        ),
    ]
