# Generated by Django 5.1.3 on 2024-11-15 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_booking_bookingdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='Destination',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
    ]
