# Generated by Django 5.1.3 on 2024-11-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_booking_bookingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Tour',
            field=models.CharField(max_length=100),
        ),
    ]
