# Generated by Django 5.1.3 on 2024-11-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='GoogleMapsImage',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='GoogleMapsLink',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='Latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='Longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
