# Generated by Django 5.1.3 on 2024-11-19 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_destination_googlemapsimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='GoogleMapsImage',
        ),
    ]
