# Generated by Django 5.1.3 on 2024-11-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_destination_googlemapslink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='DestinationId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
