# Generated by Django 5.1.3 on 2024-11-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_destination_days_destination_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
