# Generated by Django 5.1.3 on 2024-11-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_destination_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
    ]
