# Generated by Django 5.1.3 on 2024-11-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_destination_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='Image',
        ),
        migrations.AddField(
            model_name='destination',
            name='ImageURL',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
