# Generated by Django 5.1.3 on 2024-11-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_destination_image_destination_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='ImageURL',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
