# Generated by Django 5.1.3 on 2024-11-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_destination_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='ImageURL',
        ),
        migrations.AddField(
            model_name='destination',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='tour/'),
        ),
    ]
