# Generated by Django 5.1.3 on 2024-11-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_destination_imageurl_destination_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
