# Generated by Django 5.1.3 on 2024-11-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Tour',
            new_name='DestinationId',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='User',
        ),
        migrations.AddField(
            model_name='booking',
            name='UserEmail',
            field=models.EmailField(default='fahad@gamil.com', max_length=100),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
