# Generated by Django 5.1.3 on 2024-11-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_rename_tour_booking_destinationid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Tickets',
            field=models.IntegerField(default=1),
        ),
    ]
