# Generated by Django 5.1.3 on 2024-11-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_booking_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
