# Generated by Django 5.1.3 on 2024-11-26 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_wishlist_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='tour',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='api.destination'),
        ),
    ]
