# Generated by Django 5.1.3 on 2024-11-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_wishlist_tour'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='tour',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
