# Generated by Django 5.1.3 on 2024-11-26 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_wishlist_unique_together_alter_wishlist_tour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='tour',
            new_name='des',
        ),
    ]
