# Generated by Django 5.1.3 on 2024-11-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_rename_tour_wishlist_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.EmailField(default='', max_length=1000),
        ),
    ]
