# Generated by Django 5.1.3 on 2024-11-26 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_wishlist_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
    ]
