# Generated by Django 5.1.3 on 2024-11-26 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_wishlist_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'des')},
        ),
    ]
