# Generated by Django 5.1.3 on 2024-11-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_wishlist_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
