# Generated by Django 5.1.3 on 2024-11-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_wishlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='GoogleMapsLink',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
