# Generated by Django 5.1.3 on 2024-11-28 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_destination_googlemapslink_alter_wishlist_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
    ]
