# Generated by Django 5.1.3 on 2024-11-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_wishlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='des',
            field=models.IntegerField(default=0),
        ),
    ]
