# Generated by Django 5.1.3 on 2024-11-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_wishlist_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.EmailField(default='user@example.com', max_length=50),
        ),
    ]
