# Generated by Django 5.1.3 on 2024-11-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_wishlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.EmailField(db_index=True, default='user@example.com', max_length=50),
        ),
    ]
