# Generated by Django 5.1.3 on 2024-11-28 17:54

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_wishlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='session',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='Destination',
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='added_on',
            field=models.DateTimeField(default=api.models.get_default_added_on),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.EmailField(default='user@gmail.com', max_length=191),
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
    ]
